//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Baitap()
        {
            this.Chitietbaitaps = new HashSet<Chitietbaitap>();
            this.TMP2 = new HashSet<TMP2>();
        }

        public Baitap(int iD, string nAME, string dESCRIPTION, double? eXPERIENCE)
        {
            ID = iD;
            NAME = nAME;
            DESCRIPTION = dESCRIPTION;
            EXPERIENCE = eXPERIENCE;
        }

        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<double> EXPERIENCE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietbaitap> Chitietbaitaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMP2> TMP2 { get; set; }
    }
}
