//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noidung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Noidung()
        {
            this.Chitietbaihocs = new HashSet<Chitietbaihoc>();
        }

        public Noidung(int iD, byte[] hINH, string tUVUNG)
        {
            ID = iD;
            HINH = hINH;
            TUVUNG = tUVUNG;
        }

        public int ID { get; set; }
        public byte[] HINH { get; set; }
        public string TUVUNG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietbaihoc> Chitietbaihocs { get; set; }
    }
}
