//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp
    {
        public int ID { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<int> ID_TOPIC { get; set; }
    
        public virtual Nguoidung Nguoidung { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
