//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cauhoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cauhoi()
        {
            this.Chitietbaitaps = new HashSet<Chitietbaitap>();
            this.Quanlies = new HashSet<Quanly>();
        }

        public Cauhoi(int iD, string nOIDUNG, int? cORRECT_ANS_ID, string pATH_IMAGE)
        {
            ID = iD;
            NOIDUNG = nOIDUNG;
            CORRECT_ANS_ID = cORRECT_ANS_ID;
            PATH_IMAGE = pATH_IMAGE;
        }

        public int ID { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> CORRECT_ANS_ID { get; set; }
        public string PATH_IMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietbaitap> Chitietbaitaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quanly> Quanlies { get; set; }
    }
}
