//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietbaihoc
    {
        public int ID { get; set; }
        public Nullable<int> ID_BAIHOC { get; set; }
        public Nullable<int> ID_NOIDUNG { get; set; }
    
        public virtual Baihoc Baihoc { get; set; }
        public virtual Noidung Noidung { get; set; }
    }
}
