//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoidung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nguoidung()
        {
            this.Tmps = new HashSet<Tmp>();
        }

        public Nguoidung(string username, string password)
        {
            USERNAME = username;
            PASSWORD = password;
        }

        public Nguoidung(string username, string password, string cELLNUMBER, int experience) : this(username, password)
        {
            this.CELLNUMBER = cELLNUMBER;
            this.EXPERIENCE = experience;
        }

        public Nguoidung(string username, string password, string cELLNUMBER, int experience, string pATH_IMAGE) : this(username, password, cELLNUMBER, experience)
        {
            this.PATH_IMAGE = pATH_IMAGE;
        }

        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<double> EXPERIENCE { get; set; }
        public string CELLNUMBER { get; set; }
        public string PATH_IMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tmp> Tmps { get; set; }
    }
}
